run(`julia download_documents.jl`)
run(`julia summarize_documents.jl`)
run(`julia upload_embeddings.jl`)
run(`julia query_embeddings.jl`)
rm("../../../data/import/embeddings", recursive=true, force=true)