apiVersion: v1
kind: Service
metadata:
  name: {MODELTYPE}-svc
spec:
  clusterIP: None  # Headless service
  selector:
    job-name: {MODELTYPE}
  ports:
  - port: 29500
    name: dist-port
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {MODELTYPE}
spec:
  completions: {NODES}  # Total number of pods
  parallelism: {NODES}  # Run all pods in parallel
  completionMode: Indexed
  template:
    metadata:
      labels:
        job-name: {MODELTYPE}  # This matches service selector
    spec:
      containers:
      - name: trainer
        image: {IMAGE}
        command:
        - /bin/sh
        - -c
        - |
          {ENTRYPOINT}
        ports:
        - containerPort: 29500
        resources:
          requests:
            nvidia.com/gpu: 8
            nvidia.com/hostdev: 8
            memory: "512Gi"
            cpu: "32"
          limits:
            nvidia.com/gpu: 8
            nvidia.com/hostdev: 8
            memory: "512Gi"
            cpu: "32"
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: data-volume
        emptyDir: {}
      - name: dshm
        emptyDir:
          medium: Memory
      restartPolicy: Never
      subdomain: {MODELTYPE}-svc  # needed for networking between pods in the job
